window.RPG_PERSONALITY_TEST = {
  meta: {
    title: "COC 人格审判",
    subtitle: "24题测出你的 COC 四字母团桌代号",
    intro:
      "一个专门给 COC 玩家互相点名的高梗密度版本。它不负责科学，只负责揭穿你到底是侦查狗、嘴遁王、赌狗、苦主，还是那个一听“可能掉san”就说先让我看看的危险分子。",
    stats: [
      { label: "场景题", value: "24" },
      { label: "隐藏维度", value: "12" },
      { label: "正式人格", value: "16" },
      { label: "隐藏人格", value: "3" },
    ],
  },
  dimensions: [
    { code: "PUSH", name: "推进欲", description: "会不会主动把调查往前推。" },
    { code: "DIG", name: "深挖欲", description: "会不会对线索、房间和细节追查到底。" },
    { code: "SHOW", name: "表演欲", description: "会不会主动把人物演到过量。" },
    { code: "TALK", name: "社交欲", description: "会不会优先通过问话、套话、嘴遁推进。" },
    { code: "CHAOS", name: "整活欲", description: "会不会为节目效果主动碰危险选项。" },
    { code: "SAFE", name: "保命欲", description: "会不会优先保卡、保san、保命。" },
    { code: "RISK", name: "作死欲", description: "会不会忍不住去看、去摸、去试。" },
    { code: "RULE", name: "规则执念", description: "对检定、暗投、文本和流程的重视程度。" },
    { code: "LORE", name: "设定投入", description: "对背景、小传、时代感和调查员经历的投入度。" },
    { code: "PAIN", name: "吃刀程度", description: "会不会把掉san、受伤和情绪创伤认真吃进去。" },
    { code: "SUS", name: "多疑度", description: "对NPC、案发现场和KP笑容的警惕程度。" },
    { code: "LUCK", name: "骰运宿命感", description: "对 d100 结果和命运感的迷信程度。" },
  ],
  types: [
    {
      code: "CLUE",
      name: "侦查狗",
      tagline: "KP一句“过个侦查”，你能当场回血。",
      description:
        "案发现场在别人眼里是房间，在你眼里是自助餐。别人刚开始问死者怎么死的，你已经开始问抽屉、床底、地毯、墙缝、天花板和窗沿能不能都查一遍。你不是谨慎，你只是不能接受线索在你眼皮底下伪装成灰尘。",
      traits: [
        "“我想先侦查一下”是你的开场白。",
        "KP形容得越轻描淡写，你越怀疑有东西。",
        "你能把一间普通房间查出拆迁现场的效果。",
      ],
      role: "负责让每个案发现场都被查到尊严尽失。",
      share: "我测出来是 CLUE 侦查狗，案子能不能破不知道，但现场肯定要被我翻透。",
      profile: { PUSH: 2, DIG: 3, SHOW: 0, TALK: 1, CHAOS: 0, SAFE: 1, RISK: 1, RULE: 1, LORE: 1, PAIN: 1, SUS: 2, LUCK: 1 },
    },
    {
      code: "HEAR",
      name: "聆听怪",
      tagline: "门后如果有动静，你耳朵比人先过去。",
      description:
        "别人看到可疑房间会想推门，你会先把耳朵和呼吸一起贴上去。你的人生哲学是：能听出来的东西，没必要进去送。你不是胆小，你只是希望恐怖先从音频轨道里露个头。",
      traits: [
        "你对“我先聆听一下”有生理级依赖。",
        "脚步声、呼吸声、敲击声都会让你瞬间警觉。",
        "你很擅长在进去之前就先害怕一遍。",
      ],
      role: "负责给所有危险房间补一个音频前摇。",
      share: "我测出来是 HEAR 聆听怪，门能不开就不开，先让我听听死的是谁。",
      profile: { PUSH: 1, DIG: 2, SHOW: 0, TALK: 0, CHAOS: 0, SAFE: 2, RISK: 0, RULE: 1, LORE: 1, PAIN: 1, SUS: 3, LUCK: 0 },
    },
    {
      code: "BOOK",
      name: "图书馆神父",
      tagline: "别人翻尸体，你翻文献。",
      description:
        "别人遇到诡异事件第一反应是害怕，你第一反应是图书馆。越离谱的东西，你越想去查旧报纸、档案、手稿、教会记录和年代文书。你不是爱学习，你只是坚信任何邪门东西都能在纸堆里找到更邪门的前情提要。",
      traits: [
        "听到古宅、教团、旧案，你第一反应是图书馆。",
        "你喜欢把恐怖问题做成文献综述。",
        "很多人是在掉san，你是在做史料工作。",
      ],
      role: "负责把调查团从恐怖片拽成资料片。",
      share: "我测出来是 BOOK 图书馆神父，邪神再猛也得先让我查两本旧报纸。",
      profile: { PUSH: 2, DIG: 3, SHOW: 0, TALK: 1, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 1, LORE: 3, PAIN: 1, SUS: 1, LUCK: 0 },
    },
    {
      code: "PSYC",
      name: "心理学狗",
      tagline: "NPC嘴一张，你已经准备读心了。",
      description:
        "你对案发现场的兴趣，不如对人脸上那点微表情。别人问供词，你盯眼神；别人听台词，你听停顿。你不是八卦，你只是无法忍受任何NPC在你面前靠演技混过去。",
      traits: [
        "每个NPC在你眼里都像待测谎样本。",
        "你对“他刚才是不是顿了一下”这种细节很上头。",
        "别人聊剧情，你在读人。",
      ],
      role: "负责给社交回合加上一层测谎滤镜。",
      share: "我测出来是 PSYC 心理学狗，你先别说真话，让我看看你会不会先演。",
      profile: { PUSH: 1, DIG: 2, SHOW: 1, TALK: 2, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 1, LORE: 1, PAIN: 1, SUS: 2, LUCK: 0 },
    },
    {
      code: "HIDE",
      name: "苟王",
      tagline: "人被杀，就会死。卡被撕，就会哭。",
      description:
        "你不是怂，你只是对角色寿命有最朴素的尊重。别人一听地下室有异响就想下去，你先问出口、退路、掩体和最近的医院。你不追求伟大，你只追求这张卡别在今晚变成纪念品。",
      traits: [
        "你对“先活下来再说”有近乎宗教的执念。",
        "别人冲剧情，你冲逃生路线。",
        "你可能不是最勇的那个，但你常常是最后还活着的那个。",
      ],
      role: "负责提醒全队：人被杀，就会死。",
      share: "我测出来是 HIDE 苟王，人被杀就会死，卡被撕我真的会哭。",
      profile: { PUSH: 1, DIG: 1, SHOW: 0, TALK: 1, CHAOS: 0, SAFE: 3, RISK: 0, RULE: 1, LORE: 0, PAIN: 0, SUS: 2, LUCK: 1 },
    },
    {
      code: "ROLL",
      name: "赌狗",
      tagline: "d100 不只是检定，是你和宇宙的私下恩怨。",
      description:
        "关键检定前你会先深呼吸，再开始和命运谈判。你总能把普普通通一个 d100 扔成神迹或事故，主打一个成也玄学，寄也玄学。别人掷骰是在行动，你掷骰像在开坛。",
      traits: [
        "大成功和大失败都很爱来找你。",
        "你对骰运的态度已经不是概率学，而是信仰。",
        "你随手一投，常常就能把局势改成另一个剧本。",
      ],
      role: "负责让全桌重新相信玄学真的存在。",
      share: "我测出来是 ROLL 赌狗，d100 是检定，不是彩票，但我每次都投得像在上供。",
      profile: { PUSH: 1, DIG: 1, SHOW: 1, TALK: 1, CHAOS: 1, SAFE: 1, RISK: 1, RULE: 1, LORE: 0, PAIN: 1, SUS: 1, LUCK: 3 },
    },
    {
      code: "FUMB",
      name: "大失败艺术家",
      tagline: "不会每次都出事，但你一出事就值得复盘一整年。",
      description:
        "你不是不会玩，你只是把大失败这件事做得很有个人风格。别人失败最多是没过，你失败会自动长出额外情节、额外伤害和额外耻辱。你和命运之间的关系，很像命运见你就想整点节目。",
      traits: [
        "你能把一个检定失败演成一整段事故。",
        "越关键的时刻，你越容易给KP灵感。",
        "你的失误往往自带支线和笑点。",
      ],
      role: "负责把普通事故升级成回忆录。",
      share: "我测出来是 FUMB 大失败艺术家，不是我不想过，是命运每次都想拿我整活。",
      profile: { PUSH: 1, DIG: 1, SHOW: 1, TALK: 1, CHAOS: 2, SAFE: 0, RISK: 2, RULE: 0, LORE: 0, PAIN: 1, SUS: 1, LUCK: 3 },
    },
    {
      code: "ROLE",
      name: "戏精",
      tagline: "别人扮演调查员，你在拍调查员纪录片。",
      description:
        "你不只是RP，你是把调查员从纸上请到桌上来。别人说一句“我有点紧张”，你会把呼吸、停顿、眼神和语调一起演出来。你不是沉浸，你是恨不得让KP给你打补光。",
      traits: [
        "你会认真演人物看到尸体后的第一秒反应。",
        "你的人设不是写在卡上，是长在语气里。",
        "别人记剧情节点，你记自己的高光镜头。",
      ],
      role: "负责把调查片拍成文艺片。",
      share: "我测出来是 ROLE 戏精，你们在查案，我在给调查员拍纪录片。",
      profile: { PUSH: 1, DIG: 1, SHOW: 3, TALK: 2, CHAOS: 1, SAFE: 0, RISK: 1, RULE: 0, LORE: 2, PAIN: 2, SUS: 0, LUCK: 1 },
    },
    {
      code: "PAIN",
      name: "苦主",
      tagline: "别人掉san是数字，你掉san是连续剧。",
      description:
        "别人掉 san 是扣点数，你掉 san 是整个人开始过剧情。KP给你发一刀，你会默默带着后劲继续演；KP再补一刀，你能把伤口带回现实。你不是太脆弱，你只是太认真。",
      traits: [
        "角色精神状态一崩，你本人也会跟着低气压。",
        "你吃刀不是效果，而是后劲。",
        "散团了，你还在替人物难受。",
      ],
      role: "负责把剧本的痛感带出桌面。",
      share: "我测出来是 PAIN 苦主，别人掉san是数值，我掉san是连续剧。",
      profile: { PUSH: 1, DIG: 1, SHOW: 2, TALK: 1, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 0, LORE: 2, PAIN: 3, SUS: 1, LUCK: 2 },
    },
    {
      code: "LORE",
      name: "设定怪",
      tagline: "别人车卡写背景，你车卡顺手补完半个年代。",
      description:
        "你的调查员不是一张卡，是一个时代切片。别人车卡写职业和技能，你会顺手补饮食习惯、家庭关系、受教育背景和人生创伤。你不是认真，你是对时代感有一种过量热爱。",
      traits: [
        "你写背景时，常常比开团本身还上头。",
        "你会关心人物为什么会在这个年代成为这种人。",
        "调查员在你手里不像纸片，更像老照片里的人。",
      ],
      role: "负责让人物卡长出年代质感。",
      share: "我测出来是 LORE 设定怪，别人车卡填技能，我车卡顺手写完半个时代。",
      profile: { PUSH: 1, DIG: 2, SHOW: 1, TALK: 1, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 1, LORE: 3, PAIN: 2, SUS: 1, LUCK: 0 },
    },
    {
      code: "TALK",
      name: "嘴遁王",
      tagline: "能问出来的事，就没必要先挨枪子。",
      description:
        "你对调查的理解是：人嘴里也有线索。别人想破门，你想套话；别人准备斗殴，你已经在想称呼、语气和切入话题。你不是怂，你只是坚信口才也是一种武器。",
      traits: [
        "你很擅长把审讯做成社交场。",
        "你会认真斟酌每一句问话的落点。",
        "很多本来该打起来的场面，会先被你聊到气氛古怪。",
      ],
      role: "负责把社交轮打成持续输出。",
      share: "我测出来是 TALK 嘴遁王，能问出来的事，没必要先挨枪子。",
      profile: { PUSH: 1, DIG: 1, SHOW: 1, TALK: 3, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 0, LORE: 1, PAIN: 1, SUS: 1, LUCK: 1 },
    },
    {
      code: "SUSS",
      name: "疑心病",
      tagline: "NPC一笑，你先怀疑他是不是幕后黑手。",
      description:
        "你最大的特点不是会查，而是不信。NPC一笑你就觉得他有问题，KP一沉默你就觉得要暗投，队友说“没事的”你会立刻警觉。你不是多疑，你只是比全桌更早承认这个世界确实充满恶意。",
      traits: [
        "你能把普通寒暄听出审讯味。",
        "KP微笑对你来说和恐怖片BGM效果差不多。",
        "你不是总猜对，但你永远先防一手。",
      ],
      role: "负责把整桌人维持在最低限度的被害妄想里。",
      share: "我测出来是 SUSS 疑心病，不是我多疑，是你们太敢信了。",
      profile: { PUSH: 1, DIG: 2, SHOW: 0, TALK: 1, CHAOS: 0, SAFE: 2, RISK: 0, RULE: 1, LORE: 1, PAIN: 1, SUS: 3, LUCK: 1 },
    },
    {
      code: "WORK",
      name: "社畜",
      tagline: "别人来掉san，你来排调查进度表。",
      description:
        "别人来开团是娱乐，你来开团像在带项目。队友负责发癫、掉线、迷路、作死和恋爱脑，你负责记线索、收残局、盯时间、催推进。你不是主角，但你是这个调查组里唯一还在工作的人。",
      traits: [
        "你会本能地整理线索和行动顺序。",
        "没人接主线时，你最后总会自己接。",
        "你对“别再跑题了先查案”有天然发言权。",
      ],
      role: "负责让调查团不至于查着查着变成散步团。",
      share: "我测出来是 WORK 社畜，别人来掉san，我来排调查进度表。",
      profile: { PUSH: 3, DIG: 2, SHOW: 0, TALK: 1, CHAOS: 0, SAFE: 1, RISK: 0, RULE: 2, LORE: 1, PAIN: 1, SUS: 1, LUCK: 0 },
    },
    {
      code: "BANG",
      name: "斗殴哥",
      tagline: "线索有没有不知道，但你拳头已经热了。",
      description:
        "你不是不调查，你只是觉得很多问题用斗殴检定会更快。别人还在心理学和说服之间摇摆，你已经准备把桌子掀了再问。你不是纯莽，你只是把“先动手再沟通”当成一种节约时间。",
      traits: [
        "你对斗殴、手枪和散弹枪都有天然好感。",
        "社交回合一旦僵住，你拳头会先理解局势。",
        "你总觉得很多事打一顿会更明白。",
      ],
      role: "负责把调查片临时切成动作片。",
      share: "我测出来是 BANG 斗殴哥，线索不一定有，但拳头一定先到了。",
      profile: { PUSH: 1, DIG: 0, SHOW: 1, TALK: 0, CHAOS: 2, SAFE: 0, RISK: 2, RULE: 0, LORE: 0, PAIN: 0, SUS: 1, LUCK: 1 },
    },
    {
      code: "KANG",
      name: "杠精",
      tagline: "KP说“你过个灵感”，你说“凭什么是灵感”。",
      description:
        "你不一定想反对，但你一定会找到一个能反对的角度。KP口胡一句，你要找依据；判定流程少一步，你要补文本；场景描述逻辑不自洽，你要当场追责。你不是来抬杠的，你是来给守秘人做压力测试的。",
      traits: [
        "你会本能地追问判定依据。",
        "你特别擅长发现描述里的缝。",
        "KP一句“差不多这样”会让你很难受。",
      ],
      role: "负责给守秘人现场做逻辑体检。",
      share: "我测出来是 KANG 杠精，KP说“差不多”那一刻，我就知道今天得有人负责。",
      profile: { PUSH: 2, DIG: 2, SHOW: 0, TALK: 1, CHAOS: 1, SAFE: 1, RISK: 0, RULE: 3, LORE: 1, PAIN: 0, SUS: 1, LUCK: 0 },
    },
    {
      code: "MEME",
      name: "乐子人",
      tagline: "主线可以慢点，但名场面必须准时。",
      description:
        "你不一定想害队友，但你真的很想看看事情能裂到哪一步。别人看到咒物会害怕，你会觉得这段如果不碰一下也太亏了。你不是纯作死，你只是比所有人都更忠于节目效果。",
      traits: [
        "你总能把危险场景闻出乐子味。",
        "很多事故不是撞上的，是你主动把门推开的。",
        "你会让KP痛苦，但也会让全桌记你很久。",
      ],
      role: "负责让团后复盘素材丰收。",
      share: "我测出来是 MEME 乐子人，主线可以慢点，但名场面必须准时。",
      profile: { PUSH: 1, DIG: 1, SHOW: 1, TALK: 1, CHAOS: 3, SAFE: 0, RISK: 3, RULE: 0, LORE: 0, PAIN: 0, SUS: 0, LUCK: 1 },
    },
  ],
  hiddenTypes: [
    {
      code: "SANO",
      name: "SAN0",
      tagline: "掉san归掉san，但不让我看清楚我更难受。",
      description:
        "你对掉 san 的态度很不健康。KP提前提醒“这段可能会掉san”，别人准备回避，你却会说“先让我看看”。你不是不怕疯，你只是单纯好奇到底有多疯。",
      traits: [
        "听到“可能掉san”时，你会先靠近。",
        "越不该直视的东西，你越想亲眼确认。",
        "你对精神污染的探索欲已经高过求生欲。",
      ],
      role: "负责把恐怖场景试成精神耐受实验。",
      share: "我测出来是 SANO，掉san归掉san，但不让我看清楚我更难受。",
    },
    {
      code: "SCAR",
      name: "撕卡侠",
      tagline: "别人怕撕卡，你把撕卡当成结团奖励。",
      description:
        "当KP暗示“再上可能会撕卡”，别人会后退，你会把这句话听成一种邀请。你不是不珍惜角色，你只是对壮烈退场和临终高光有一种过量浪漫化。别人撕卡是事故，你撕卡像计划的一部分。",
      traits: [
        "越到快死的时候，你越像突然开了演出模式。",
        "你嘴上说再看看，身体已经准备好跟怪物拼了。",
        "你会把撕卡这件事说得像某种荣耀。",
      ],
      role: "负责让KP意识到有人是真把撕卡当终极成就。",
      share: "我测出来是 SCAR 撕卡侠，卡不是不能撕，主要得撕得有排面。",
    },
    {
      code: "KPSD",
      name: "坏KP受害者",
      tagline: "KP一笑，你就开始写遗书。",
      description:
        "你对守秘人的基本信任已经低到近乎破产。KP说“你过个灵感”，你会觉得自己马上要下葬；KP笑而不语，你会默认这波肯定不是好事。你不是冤枉KP，你只是长期被训练出了条件反射。",
      traits: [
        "KP一笑，你就觉得这波要坏。",
        "你会把很多普通检定自动翻译成死亡预告。",
        "你对守秘人的善意基本只保留礼貌层面。",
      ],
      role: "负责把KP的每个微笑解释成系统公告。",
      share: "我测出来是 KPSD 坏KP受害者，KP一笑，我就默认这把是头七局。",
    },
  ],
  specialFlows: [
    {
      key: "sano",
      hiddenTypeCode: "SANO",
      priority: 3,
      note: "隐藏人格已触发：你的调查员还没疯透，但你本人已经对掉san形成了稳定兴趣。",
      insertRange: [7, 16],
      entry: {
        id: "CSP1",
        special: true,
        badge: "彩蛋题 · 掉san预警",
        text: "KP提前提醒“这段你们可能会掉san”，你第一反应最像？",
        options: [
          { label: "谢谢提醒，我先后撤。", value: 0 },
          { label: "先让别人看看，我听复述也行。", value: 1 },
          { label: "到底是什么？你先描述一点。", value: 2 },
          { label: "掉san归掉san，你先让我看全。", value: 3 },
        ],
      },
      followUp: {
        id: "CSP2",
        special: true,
        badge: "彩蛋题 · 再看一眼",
        text: "面对明显不该直视的东西时，你真实态度更接近？",
        options: [
          { label: "能不看就不看，命比较重要。", value: 0 },
          { label: "别人看完复述给我就行。", value: 1 },
          { label: "我知道会出事，但还是想自己确认。", value: 2 },
          { label: "不让我亲眼看清楚，我今晚会后悔。", value: 3 },
        ],
      },
      triggerValues: [2, 3],
      hiddenTriggerValues: [2, 3],
    },
    {
      key: "scar",
      hiddenTypeCode: "SCAR",
      priority: 2,
      note: "隐藏人格已触发：别人怕撕卡，你已经开始思考怎么把退场台词说得更帅。",
      insertRange: [14, 24],
      entry: {
        id: "CSP3",
        special: true,
        badge: "彩蛋题 · 撕卡边缘",
        text: "KP暗示“再往前走可能真的会撕卡”，你第一反应最像？",
        options: [
          { label: "那就不走，活着最重要。", value: 0 },
          { label: "先让别人顶，我看看情况。", value: 1 },
          { label: "撕卡就撕卡，至少得把这段看完。", value: 2 },
          { label: "如果要撕，那也得撕得像个人物结局。", value: 3 },
        ],
      },
      followUp: {
        id: "CSP4",
        special: true,
        badge: "彩蛋题 · 临终高光",
        text: "你对“撕卡”这件事的真实态度更接近？",
        options: [
          { label: "纯事故，能避免最好避免。", value: 0 },
          { label: "只要不是我，谁撕都行。", value: 1 },
          { label: "如果够帅，撕卡也不是不能接受。", value: 2 },
          { label: "新卡模板我都能接受，主要旧卡得死得漂亮。", value: 3 },
        ],
      },
      triggerValues: [2, 3],
      hiddenTriggerValues: [2, 3],
    },
    {
      key: "kpsd",
      hiddenTypeCode: "KPSD",
      priority: 1,
      note: "隐藏人格已触发：守秘人只是笑了一下，但你已经默认这是场头七局。",
      insertRange: [5, 18],
      entry: {
        id: "CSP5",
        special: true,
        badge: "彩蛋题 · 守秘人微笑",
        text: "KP笑着说“你过个灵感”，你第一反应最像？",
        options: [
          { label: "正常检定，我过一下。", value: 0 },
          { label: "有点不妙，但先投吧。", value: 1 },
          { label: "坏了，守秘人在给我上坟。", value: 2 },
          { label: "这笑容我认识，通常后面都跟着事故。", value: 3 },
        ],
      },
      followUp: {
        id: "CSP6",
        special: true,
        badge: "彩蛋题 · 信任危机",
        text: "你对KP的基本信任度更接近？",
        options: [
          { label: "他是中立的，我愿意相信。", value: 0 },
          { label: "大体能信，但得留点心眼。", value: 1 },
          { label: "我知道他在笑，但我也知道这笑一般不白笑。", value: 2 },
          { label: "没有，我只是在礼貌地陪他演。", value: 3 },
        ],
      },
      triggerValues: [2, 3],
      hiddenTriggerValues: [2, 3],
    },
  ],
  questions: [
    { id: "CQ1", dim: "PUSH", text: "KP说“你们到达案发现场”，你最像哪句？", options: [
      { label: "先等等，看看别人怎么动。", value: 0 },
      { label: "先把最关键的调查方向定下来。", value: 3 },
      { label: "我先演一段调查员到场反应。", value: 1 },
      { label: "先问现场能不能侦查。", value: 2 },
    ]},
    { id: "CQ2", dim: "PUSH", text: "大家围着尸体聊了五分钟还没开始查，你会？", options: [
      { label: "继续听，反正总有人急。", value: 0 },
      { label: "差不多了，先把调查顺序排一下。", value: 3 },
      { label: "我先记记队友发言。", value: 1 },
      { label: "趁他们聊，我先偷偷翻现场。", value: 2 },
    ]},
    { id: "CQ3", dim: "DIG", text: "KP说“这房间看起来很普通”，你最像？", options: [
      { label: "普通就普通，继续走。", value: 0 },
      { label: "柜子、床底、地毯、窗台都查。", value: 3 },
      { label: "先看队友会不会先动。", value: 1 },
      { label: "越普通越可疑。", value: 2 },
    ]},
    { id: "CQ4", dim: "DIG", text: "NPC随口提到一个旧地名，别人没反应，你会？", options: [
      { label: "先不管，主线更重要。", value: 0 },
      { label: "记一下，也许后面能用。", value: 1 },
      { label: "当场追问，问到他后悔多嘴。", value: 3 },
      { label: "我默认这是伏笔。", value: 2 },
    ]},
    { id: "CQ5", dim: "SHOW", text: "调查员第一次在众人面前亮相时，你通常会？", options: [
      { label: "简单交代身份就够。", value: 1 },
      { label: "给我完整出场，我这人物不是白车的。", value: 3 },
      { label: "先看桌上气氛，再决定演多少。", value: 2 },
      { label: "能省就省，低调一点。", value: 0 },
    ]},
    { id: "CQ6", dim: "SHOW", text: "当你的调查员看见尸体时，你更可能？", options: [
      { label: "简单表述一下反应。", value: 1 },
      { label: "认真演一段，让全桌都知道我人设崩了。", value: 3 },
      { label: "看情况补几句，不抢太多戏。", value: 2 },
      { label: "我尽量快点进调查环节。", value: 0 },
    ]},
    { id: "CQ7", dim: "TALK", text: "目击者明显藏了话，你会？", options: [
      { label: "先聊，把他嘴撬开。", value: 3 },
      { label: "先观察他表情和动作。", value: 1 },
      { label: "直接问重点，别绕。", value: 2 },
      { label: "聊不动就准备换手段。", value: 0 },
    ]},
    { id: "CQ8", dim: "TALK", text: "队友想直接动粗时，你最像哪句？", options: [
      { label: "等等，我再试着套两句。", value: 3 },
      { label: "也行，快点结束。", value: 0 },
      { label: "先看看动粗值不值。", value: 1 },
      { label: "打之前我先补最后一个问题。", value: 2 },
    ]},
    { id: "CQ9", dim: "CHAOS", text: "案发现场有件明显很邪门的遗物，你会？", options: [
      { label: "离远点，别乱碰。", value: 0 },
      { label: "我嘴上劝，心里其实很想看。", value: 1 },
      { label: "先拿棍子戳一下看看。", value: 2 },
      { label: "不碰一下今晚都睡不着。", value: 3 },
    ]},
    { id: "CQ10", dim: "CHAOS", text: "本来是严肃恐怖场面，突然出现一个很适合整活的空档，你会？", options: [
      { label: "忍住，别破坏氛围。", value: 0 },
      { label: "小整一下，调调气氛。", value: 1 },
      { label: "看KP脸色，能整就狠狠干。", value: 2 },
      { label: "不整这一下对不起我来过。", value: 3 },
    ]},
    { id: "CQ11", dim: "SAFE", text: "地下室里大概率有东西，你会？", options: [
      { label: "先看退路。", value: 3 },
      { label: "让更适合的人先下去。", value: 2 },
      { label: "直接冲，拖久了更难受。", value: 0 },
      { label: "先聆听、侦查、确认一轮。", value: 2 },
    ]},
    { id: "CQ12", dim: "SAFE", text: "你HP和san都不太健康，但前面还有关键线索，你会？", options: [
      { label: "先保卡，线索总有别的办法。", value: 3 },
      { label: "看队伍怎么走，我尽量跟上。", value: 1 },
      { label: "都到这了，再拼一下。", value: 0 },
      { label: "先判断这波值不值。", value: 2 },
    ]},
    { id: "CQ13", dim: "RISK", text: "桌上摆着一本明显不该翻开的书，你最像？", options: [
      { label: "不翻。", value: 0 },
      { label: "隔远点先观察一下。", value: 1 },
      { label: "我知道不该翻，但真的很想翻。", value: 2 },
      { label: "别人还在劝，我已经翻到第二页了。", value: 3 },
    ]},
    { id: "CQ14", dim: "RISK", text: "你明知某扇门后八成有大问题，但线索大概率也在里面，你会？", options: [
      { label: "先换别的路。", value: 0 },
      { label: "如果别人先上，我跟。", value: 1 },
      { label: "纠结三秒，然后开。", value: 2 },
      { label: "不进这门，我今晚会惦记。", value: 3 },
    ]},
    { id: "CQ15", dim: "RULE", text: "KP说“这里今天先这么判”，你第一反应更像？", options: [
      { label: "行吧，能跑就行。", value: 0 },
      { label: "记下来，散团后再翻规则。", value: 1 },
      { label: "我会温和地问一句依据。", value: 2 },
      { label: "没有依据？那我现在就找。", value: 3 },
    ]},
    { id: "CQ16", dim: "RULE", text: "你对暗投、灵感、侦查流程的态度更接近？", options: [
      { label: "差不多能跑就够了。", value: 0 },
      { label: "常用流程清楚就行。", value: 1 },
      { label: "关键流程我会特地记。", value: 2 },
      { label: "文本和流程不清楚我会难受。", value: 3 },
    ]},
    { id: "CQ17", dim: "LORE", text: "车调查员卡时你最容易在哪一步上头？", options: [
      { label: "先把技能数值配明白。", value: 0 },
      { label: "人设关键词写到能演就行。", value: 1 },
      { label: "背景、关系、经历我都想补。", value: 2 },
      { label: "我会认真想这个人为什么会查这种案子。", value: 3 },
    ]},
    { id: "CQ18", dim: "LORE", text: "KP提到年代背景或旧案资料时，你会？", options: [
      { label: "跟主线相关再说。", value: 0 },
      { label: "先记一下。", value: 1 },
      { label: "我会开始想它和人物背景怎么咬上。", value: 2 },
      { label: "这东西不搞懂我会非常难受。", value: 3 },
    ]},
    { id: "CQ19", dim: "PAIN", text: "调查员掉了一大口san后，你一般会？", options: [
      { label: "演一下就切回来。", value: 0 },
      { label: "会难受一会儿，但还能收住。", value: 1 },
      { label: "我会认真把这个状态吃进去。", value: 2 },
      { label: "别问，我现在和调查员一起在发疯。", value: 3 },
    ]},
    { id: "CQ20", dim: "PAIN", text: "散团后你最像哪句？", options: [
      { label: "这个本流程设计不错。", value: 0 },
      { label: "刚那段真的笑死我了。", value: 1 },
      { label: "我人物那会儿其实已经快绷不住了。", value: 2 },
      { label: "我到现在还没从那一刀里缓过来。", value: 3 },
    ]},
    { id: "CQ21", dim: "SUS", text: "NPC冲你笑了一下，你默认？", options: [
      { label: "正常礼貌互动。", value: 0 },
      { label: "先观望，不急着定性。", value: 1 },
      { label: "这个笑里肯定藏了东西。", value: 2 },
      { label: "好，记上，后面重点盯这个人。", value: 3 },
    ]},
    { id: "CQ22", dim: "SUS", text: "KP笑而不语地看着你们时，你脑内弹幕更像？", options: [
      { label: "正常，先继续。", value: 0 },
      { label: "有点不妙，但先过。", value: 1 },
      { label: "坏了，这笑容后面一般不跟好事。", value: 2 },
      { label: "我已经默认这局要出人命了。", value: 3 },
    ]},
    { id: "CQ23", dim: "LUCK", text: "连续几个检定都寄了之后，你更像？", options: [
      { label: "正常波动，问题不大。", value: 0 },
      { label: "有点烦，但还能接受。", value: 1 },
      { label: "今天这 d100 明显在搞我。", value: 2 },
      { label: "命运今天就是冲我来的。", value: 3 },
    ]},
    { id: "CQ24", dim: "LUCK", text: "关键检定前，你心里最像哪句？", options: [
      { label: "过不过都行，先扔。", value: 0 },
      { label: "稳一点，别太离谱。", value: 1 },
      { label: "坏了，我感觉又要大失败。", value: 2 },
      { label: "来，让我看看这把是谁先疯。", value: 3 },
    ]},
  ],
};
